// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:flutter_app/models/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BackupFrequencyAdapter());
    registerAdapter(BackupSyncStateAdapter());
    registerAdapter(BankAccountAdapter());
    registerAdapter(BillingDetailsAdapter());
    registerAdapter(CompanyAdapter());
    registerAdapter(CustomerAdapter());
    registerAdapter(ExpenseCategoryAdapter());
    registerAdapter(ExpenseRecordAdapter());
    registerAdapter(FinancialSummaryAdapter());
    registerAdapter(OrderAdapter());
    registerAdapter(OrderChargesAdapter());
    registerAdapter(OrderExpensesAdapter());
    registerAdapter(OrderNoteItemAdapter());
    registerAdapter(OrderStatusAdapter());
    registerAdapter(PayerTypeAdapter());
    registerAdapter(PaymentAllocationAdapter());
    registerAdapter(PaymentMethodAdapter());
    registerAdapter(PaymentReceiptAdapter());
    registerAdapter(PaymentStatusAdapter());
    registerAdapter(SyncStatusAdapter());
    registerAdapter(TransporterProfileAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BackupFrequencyAdapter());
    registerAdapter(BackupSyncStateAdapter());
    registerAdapter(BankAccountAdapter());
    registerAdapter(BillingDetailsAdapter());
    registerAdapter(CompanyAdapter());
    registerAdapter(CustomerAdapter());
    registerAdapter(ExpenseCategoryAdapter());
    registerAdapter(ExpenseRecordAdapter());
    registerAdapter(FinancialSummaryAdapter());
    registerAdapter(OrderAdapter());
    registerAdapter(OrderChargesAdapter());
    registerAdapter(OrderExpensesAdapter());
    registerAdapter(OrderNoteItemAdapter());
    registerAdapter(OrderStatusAdapter());
    registerAdapter(PayerTypeAdapter());
    registerAdapter(PaymentAllocationAdapter());
    registerAdapter(PaymentMethodAdapter());
    registerAdapter(PaymentReceiptAdapter());
    registerAdapter(PaymentStatusAdapter());
    registerAdapter(SyncStatusAdapter());
    registerAdapter(TransporterProfileAdapter());
  }
}
